databases:
  - name: goodwill_db
    plan: free

services:
  - type: web
    name: backend
    env: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: goodwill_db
          property: connectionString

  - type: web
    name: frontend
    env: node
    buildCommand: pwd && ls -R
    startCommand: cd frontend && next start -p $PORT
    envVars:
      - key: NEXT_PUBLIC_BACKEND_URL
        fromService:
          type: web
          name: backend
          property: url

    build_env_vars:
      - key: NEXT_PUBLIC_BACKEND_URL
        fromService:
          type: web
          name: backend
          property: url 