databases:
  - name: goodwill_db
    plan: starter

services:
  - type: web
    name: backend
    env: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: goodwill_db
          property: connectionString

  - type: web
    name: frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: next start -p $PORT
    envVars:
      - key: NEXT_PUBLIC_BACKEND_URL
        fromService:
          type: web
          name: backend
          property: url 