databases:
  - name: goodwill_db
    databaseName: goodwill_db
    user: goodwill_user
    plan: free

services:
  - type: web
    name: backend
    env: docker
    repo: https://github.com/nbrain-team/goodwill.git
    region: oregon
    plan: starter
    branch: master
    rootDir: backend
    dockerfilePath: ./Dockerfile
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: goodwill_db
          property: connectionString

  - type: web
    name: frontend
    env: node
    repo: https://github.com/nbrain-team/goodwill.git
    region: oregon
    plan: starter
    branch: master
    rootDir: frontend
    buildFilter:
      paths:
      - frontend/**
    build_command: npm install && npm run build
    start_command: next start -p $PORT
    env_vars:
      - key: NEXT_PUBLIC_BACKEND_URL
        fromService:
          type: web
          name: backend
          property: url 