databases:
  - name: goodwill_db
    plan: starter

services:
  - type: web
    name: backend
    env: docker
    plan: starter
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: goodwill_db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false

  - type: web
    name: frontend
    env: node
    plan: starter
    buildCommand: npm install --prefix frontend && npm run build --prefix frontend
    startCommand: npm start --prefix frontend 