databases:
  - name: goodwill_db
    plan: free

services:
  - type: web
    name: backend
    env: docker
    plan: starter
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: goodwill_db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false

  - type: web
    name: frontend
    env: node
    plan: starter
    buildCommand: ls -R
    startCommand: cd frontend && npm start
    envVars:
      - key: NEXT_PUBLIC_BACKEND_URL
        fromService:
          type: web
          name: backend
          property: hostport 